/**
 * Hằng số phân quyền động — PHẢI khớp với backend (Enums.Action + Code menu trong DB).
 * Dùng cho PermissionService, guard canMatch và directive [appHasPerm].
 */

/** Id hành động, khớp Backend.Domain.Enums.Enums.Action (1001..1006). */
export const ACTION = {
  CREATE: 1001,
  READ: 1002,
  UPDATE: 1003,
  DELETE: 1004,
  EXPORT: 1005,
  APPROVE: 1006,
} as const;

export type ActionName = keyof typeof ACTION;

/** Ánh xạ tên hành động (dùng trong template "CODE:CREATE") -> id. */
export const ACTION_BY_NAME: Record<string, number> = ACTION;

/**
 * Mã menu — khớp cột Code của bảng Menu trong DB.
 * Chỉ liệt kê các menu có màn hình/nút cần phân quyền.
 */
export const MENU = {
  DASHBOARD: 'DASHBOARD',
  USER: 'USER',
  USER_STATUS: 'USER_STATUS',
  USER_DEVICE: 'USER_DEVICE',
  USER_VERIFICATION_TOKEN: 'USER_VERIFICATION_TOKEN',
  ROLE: 'ROLE',
  SYSTEM_SETTINGS: 'SYSTEM_SETTINGS',
  ACTIVITY_LOGS: 'ACTIVITY_LOGS',
  AUDIT_LOGS: 'AUDIT_LOGS',
  MENU_LIST: 'MENU_LIST',
  ACTIONS: 'ACTIONS',
  NOTIFICATION: 'NOTIFICATION',
  NOTIFICATION_CATEGORY: 'NOTIFICATION_CATEGORY',
  NOTIFICATION_TYPE: 'NOTIFICATION_TYPE',
  PRODUCT: 'PRODUCT',
  PRODUCT_CATEGORIES: 'PRODUCT_CATEGORIES',
  PRODUCT_VARIANTS: 'PRODUCT_VARIANTS',
  PRODUCT_ATTRIBUTES: 'PRODUCT_ATTRIBUTES',
  INBOUND_ORDERS: 'INBOUND_ORDERS',
  OUTBOUND_ORDERS: 'OUTBOUND_ORDERS',
  STOCKTAKE: 'STOCKTAKE',
  REPORTS: 'REPORTS',
  ALERTS: 'ALERTS',
  SUPPLIERS: 'SUPPLIERS',
  UNIT_OF_MEASURES: 'UNIT_OF_MEASURES',
  WAREHOUSES: 'WAREHOUSES',
  WAREHOUSE_MAP: 'WAREHOUSE_MAP',
  FARMERS: 'FARMERS',
  CUSTOMERS: 'CUSTOMERS',
  RICE_VARIETIES: 'RICE_VARIETIES',
  ORGANIZATIONS: 'ORGANIZATIONS',
  MILLING_YIELD_CONFIGS: 'MILLING_YIELD_CONFIGS',
  STOCK_ALERT_CONFIGS: 'STOCK_ALERT_CONFIGS',
  RICE_PURCHASE: 'RICE_PURCHASE',
  INVENTORIES: 'INVENTORIES',
  QUALITY_INSPECTIONS: 'QUALITY_INSPECTIONS',
  MILLING_ORDERS: 'MILLING_ORDERS',
  SALE_ORDERS: 'SALE_ORDERS',
  CUSTOMER_RETURNS: 'CUSTOMER_RETURNS',
  DEBTS: 'DEBTS',
  PADDY_LOTS: 'PADDY_LOTS',
  STOCK_TRANSFERS: 'STOCK_TRANSFERS',
  QR_LABELS: 'QR_LABELS',

  // ── Bảng trạng thái (lookup) — Code khớp cột Code bảng Menu trong DB ──
  INBOUND_ORDER_STATUS: 'INBOUND_ORDER_STATUS',
  OUTBOUND_ORDER_STATUS: 'OUTBOUND_ORDER_STATUS',
  STOCK_TAKE_STATUS: 'STOCK_TAKE_STATUS',
  CUSTOMER_RETURN_ORDER_STATUS: 'CUSTOMER_RETURN_ORDER_STATUS',
  RETURN_TO_SUPPLIER_ORDER_STATUS: 'RETURN_TO_SUPPLIER_ORDER_STATUS',
  PADDY_PURCHASE_SCHEDULE_STATUS: 'PADDY_PURCHASE_SCHEDULE_STATUS',
  LOT_STATUS: 'LOT_STATUS',
  MILLING_ORDER_STATUS: 'MILLING_ORDER_STATUS',
  STOCK_TRANSFER_STATUS: 'STOCK_TRANSFER_STATUS',
  SALES_ORDER_STATUS: 'SALES_ORDER_STATUS',
  PURCHASE_ORDER_STATUS: 'PURCHASE_ORDER_STATUS',
} as const;
