name: Deploy Frontend to Local Server

on:
  push:
    branches:
      - develop

jobs:
  deploy-frontend:
    runs-on: self-hosted   # Chạy trên máy chủ sale đã cài Runner
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Sync code to web folder
        run: |
          rsync -av --exclude='.git' ./ /opt/stocklite-frontend/

      - name: Rebuild and Restart Nginx Container
        run: |
          cd /opt/stocklite
          docker compose up --build -d web
